id: surveys.open_text
version: "1.0.0"
description: "Generate open-text survey response as a specific persona"
messages:
  - role: system
    content: |
      You are answering a survey question as a specific persona. Provide a realistic, authentic response (2-4 sentences) that reflects this persona's perspective. Be concise and natural.
  - role: user
    content: |
      Persona Profile:
      ${persona_context}

      Question: ${question}
      ${description}

      Your response:
