# ==============================================================================
# cloudbuild.yaml - Optimized CI/CD Pipeline
# ==============================================================================
# Pipeline stages:
# 1. BUILD: Docker image (frontend + backend) with layer caching
# 2. PUSH: Push to Artifact Registry
# 3. MIGRATE: Database migrations (before deploy)
# 4. DEPLOY: Cloud Run service
# 5. NEO4J INIT: Initialize vector indexes
# 6. SMOKE TESTS: Post-deployment verification (health + frontend)
#
# Total time: ~8-12 min (with BuildKit inline cache + pinned base images)
#   - First build (cold cache): ~20-25 min
#   - Incremental builds (warm cache): ~8-12 min
#   - Code-only changes (hot cache): ~5-8 min
# Optimization: BuildKit inline cache + pinned node:20.18.0/python:3.11.11
# Code quality checks: Run locally (ruff, mypy, pytest)
# ==============================================================================

steps:
  # ==========================================================================
  # PULL CACHE: Download previous image for layer caching
  # ==========================================================================
  # This step pulls the latest image from Artifact Registry to use as cache source
  # Uses 'entrypoint: bash' with '|| true' to avoid failing on first build (no cache exists yet)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest || echo "No cache image found - first build will be slow"
    id: 'pull-cache'
    waitFor: ['-']  # Start immediately (parallel with tests if any)

  # ==========================================================================
  # BUILD: Docker Image (Backend + Frontend) with BuildKit Inline Cache
  # ==========================================================================
  # BuildKit inline cache: zapisuje cache metadata WEWNĄTRZ image
  # To umożliwia cache multi-stage builds (frontend-builder, backend-builder, runtime)
  # --cache-from: reuse cache z poprzednich buildów
  # --cache-to type=inline: zapisz cache metadata dla przyszłych buildów
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Setup BuildKit (nowszy backend Docker z lepszym cachingiem)
        export DOCKER_BUILDKIT=1

        # Build z inline cache (zapisuje cache metadata w image layers)
        docker build \
          -f Dockerfile.cloudrun \
          --cache-from europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest \
          -t europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:$COMMIT_SHA \
          .
    id: 'build'
    waitFor: ['pull-cache']  # Wait for cache image to be pulled
    env:
      - 'DOCKER_BUILDKIT=1'

  # ==========================================================================
  # PUSH: Docker Image to Artifact Registry
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight'
    id: 'push'
    waitFor: ['build']

  # ==========================================================================
  # MIGRATE: Database Migrations (BEFORE deploy)
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Run database migrations via Cloud Run Jobs
        # This ensures schema is up-to-date BEFORE deploying new code
        echo "🔄 Running database migrations..."

        # Check if migration job exists, create if not
        if ! gcloud run jobs describe db-migrate --region=europe-central2 2>/dev/null; then
          echo "Creating migration job..."
          gcloud run jobs create db-migrate \
            --image=europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest \
            --region=europe-central2 \
            --add-cloudsql-instances=gen-lang-client-0508446677:europe-central2:sight \
            --set-secrets=DATABASE_URL=DATABASE_URL_CLOUD:latest \
            --set-env-vars=PYTHONUNBUFFERED=1,PYTHONPATH=/app \
            --command=bash \
            --args=scripts/run_migrations_cloudrun.sh \
            --max-retries=2 \
            --task-timeout=300
        else
          echo "Updating migration job image..."
          gcloud run jobs update db-migrate \
            --image=europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest \
            --region=europe-central2 \
            --set-env-vars=PYTHONUNBUFFERED=1,PYTHONPATH=/app
        fi

        # Execute migrations
        echo "Executing migrations..."
        gcloud run jobs execute db-migrate --region=europe-central2 --wait

        # Check migration status
        if [ $$? -eq 0 ]; then
          echo "✅ Migrations completed successfully"
        else
          echo "❌ Migrations failed - aborting deployment"
          exit 1
        fi
    id: 'migrate'
    waitFor: ['push']

  # ==========================================================================
  # DEPLOY STAGING: Cloud Run Service (sight-staging) - Before production
  # DISABLED: Staging environment not configured (missing secrets)
  # ==========================================================================
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  #   entrypoint: 'gcloud'
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - 'sight-staging'
  #     - '--image=europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:$COMMIT_SHA'
  #     - '--region=europe-central2'
  #     - '--platform=managed'
  #     - '--allow-unauthenticated'
  #     - '--port=8080'
  #     - '--memory=4Gi'
  #     - '--cpu=2'
  #     - '--cpu-boost'
  #     - '--timeout=300'
  #     - '--min-instances=0'
  #     - '--max-instances=3'  # Lower limit for staging
  #     - '--execution-environment=gen2'
  #     - '--add-cloudsql-instances=gen-lang-client-0508446677:europe-central2:sight-staging'
  #     - '--set-secrets=DATABASE_URL=DATABASE_URL_STAGING:latest,GOOGLE_API_KEY=GOOGLE_API_KEY_STAGING:latest,NEO4J_PASSWORD=NEO4J_PASSWORD_STAGING:latest,NEO4J_URI=NEO4J_URI_STAGING:latest,POSTGRES_PASSWORD=POSTGRES_PASSWORD_STAGING:latest,REDIS_URL=REDIS_URL_STAGING:latest,SECRET_KEY=SECRET_KEY_STAGING:latest'
  #     - '--set-env-vars=NEO4J_USER=neo4j,ENVIRONMENT=staging,DEBUG=True,DEFAULT_LLM_PROVIDER=google,DEFAULT_MODEL=gemini-2.5-flash,GRAPH_MODEL=gemini-2.5-flash,PERSONA_GENERATION_MODEL=gemini-2.5-flash,ANALYSIS_MODEL=gemini-2.5-pro,EMBEDDING_MODEL=models/gemini-embedding-001,TEMPERATURE=0.7,MAX_TOKENS=6000,RAG_ENABLED=True,RAG_USE_HYBRID_SEARCH=True,RAG_USE_RERANKING=False,RAG_RERANK_CANDIDATES=5,RETRIEVAL_MODE=hybrid,RAG_CHUNK_SIZE=1000,RAG_CHUNK_OVERLAP=300,RAG_TOP_K=8,RAG_VECTOR_WEIGHT=0.7,RAG_RRF_K=60,ORCHESTRATION_ENABLED=True,ORCHESTRATION_TIMEOUT=90,TRANSFORMERS_VERBOSITY=error,HF_HUB_DISABLE_TELEMETRY=1,WORKFLOWS_ENABLED=true,GCP_PROJECT_ID=gen-lang-client-0508446677,GCP_REGION=europe-central2'
  #   id: 'deploy-staging'
  #   waitFor: ['migrate']

  # ==========================================================================
  # SMOKE TESTS STAGING: Verify staging deployment before production
  # DISABLED: Staging environment not configured
  # ==========================================================================
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  #   id: 'smoke-tests-staging'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       echo "🔥 Running smoke tests on STAGING..."
  #       # ... (staging tests disabled - no staging environment)
  #   waitFor: ['deploy-staging']

  # ==========================================================================
  # DEPLOY PRODUCTION: Cloud Run Service (sight) with traffic splitting
  # ==========================================================================
  # Strategy: Deploy new revision with NO-TRAFFIC initially
  # Then gradually promote: 0% → 10% → 100%
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Deploying new revision to production (direct deployment, 100% traffic)..."

        # Deploy new revision directly with 100% traffic (simpler for small projects)
        gcloud run deploy sight \
          --image=europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest \
          --region=europe-central2 \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --memory=4Gi \
          --cpu=2 \
          --cpu-boost \
          --timeout=300 \
          --min-instances=0 \
          --max-instances=5 \
          --execution-environment=gen2 \
          --add-cloudsql-instances=gen-lang-client-0508446677:europe-central2:sight \
          --set-secrets=DATABASE_URL=DATABASE_URL_CLOUD:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest,NEO4J_PASSWORD=NEO4J_PASSWORD:latest,NEO4J_URI=NEO4J_URI:latest,POSTGRES_PASSWORD=POSTGRES_PASSWORD:latest,REDIS_URL=REDIS_URL:latest,SECRET_KEY=SECRET_KEY:latest \
          --set-env-vars=NEO4J_USER=neo4j,ENVIRONMENT=production,DEBUG=False,DEFAULT_LLM_PROVIDER=google,DEFAULT_MODEL=gemini-2.5-flash,GRAPH_MODEL=gemini-2.5-flash,PERSONA_GENERATION_MODEL=gemini-2.5-flash,ANALYSIS_MODEL=gemini-2.5-pro,EMBEDDING_MODEL=models/gemini-embedding-001,TEMPERATURE=0.7,MAX_TOKENS=6000,RAG_ENABLED=True,RAG_USE_HYBRID_SEARCH=True,RAG_USE_RERANKING=False,RAG_RERANK_CANDIDATES=5,RETRIEVAL_MODE=hybrid,RAG_CHUNK_SIZE=1000,RAG_CHUNK_OVERLAP=300,RAG_TOP_K=8,RAG_VECTOR_WEIGHT=0.7,RAG_RRF_K=60,ORCHESTRATION_ENABLED=True,ORCHESTRATION_TIMEOUT=90,TRANSFORMERS_VERBOSITY=error,HF_HUB_DISABLE_TELEMETRY=1,WORKFLOWS_ENABLED=true,GCP_PROJECT_ID=gen-lang-client-0508446677,GCP_REGION=europe-central2

        echo "✅ Production deployed successfully with 100% traffic"
    id: 'deploy-production'
    waitFor: ['migrate']  # Deploy production directly after migration (staging disabled)

  # ==========================================================================
  # NEO4J INIT: Initialize Neo4j Indexes (AFTER production deploy)
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Initialize Neo4j indexes via Cloud Run Jobs
        # This ensures vector indexes exist for RAG system
        echo "🔄 Initializing Neo4j indexes..."

        # Check if neo4j-init job exists, create if not
        if ! gcloud run jobs describe neo4j-init --region=europe-central2 2>/dev/null; then
          echo "Creating Neo4j init job..."
          gcloud run jobs create neo4j-init \
            --image=europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest \
            --region=europe-central2 \
            --set-secrets=NEO4J_URI=NEO4J_URI:latest,NEO4J_PASSWORD=NEO4J_PASSWORD:latest \
            --set-env-vars=NEO4J_USER=neo4j \
            --command=python,scripts/init_neo4j_cloudrun.py \
            --max-retries=3 \
            --task-timeout=300
        else
          echo "Updating Neo4j init job image..."
          gcloud run jobs update neo4j-init \
            --image=europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest \
            --region=europe-central2
        fi

        # Execute Neo4j initialization
        echo "Executing Neo4j index initialization..."
        gcloud run jobs execute neo4j-init --region=europe-central2 --wait

        # Check initialization status (non-fatal - RAG services have retry logic)
        if [ $$? -eq 0 ]; then
          echo "✅ Neo4j indexes initialized successfully"
        else
          echo "⚠️  Neo4j init failed - RAG features may be limited"
          echo "   Check logs: gcloud run jobs executions logs [EXECUTION_ID]"
          echo "   App will continue to run, but RAG functionality may be unavailable"
        fi
    id: 'neo4j-init'
    waitFor: ['deploy-production']

  # ==========================================================================
  # SMOKE TESTS & TRAFFIC PROMOTION: DISABLED
  # ==========================================================================
  # Smoke tests and gradual traffic promotion disabled for simpler deployment.
  # Application deployed directly with 100% traffic after neo4j init.
  # For canary deployment strategy, see git history.

# Output images
images:
  - 'europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'  # Fast build (frontend + backend multi-stage)
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'
