# ==============================================================================
# cloudbuild.yaml - Single Service Deployment (Backend + Frontend Static)
# ==============================================================================
# Builds one Docker image containing:
# - FastAPI backend
# - React frontend (static files in /static/)
# Deploys to Cloud Run service: sight
# ==============================================================================

steps:
  # ==========================================================================
  # BUILD: Docker Image (Backend + Frontend)
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '-t'
      - 'europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest'
      - '-t'
      - 'europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:$COMMIT_SHA'
      - '.'
    id: 'build'

  # ==========================================================================
  # PUSH: Docker Image to Artifact Registry
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight'
    id: 'push'
    waitFor: ['build']

  # ==========================================================================
  # DEPLOY: Cloud Run Service (sight)
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sight'
      - '--image=europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest'
      - '--region=europe-central2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=2Gi'  # Więcej RAM dla frontend assets
      - '--cpu=1'
      - '--timeout=300'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--add-cloudsql-instances=gen-lang-client-0508446677:europe-central2:sight'
      - '--set-secrets=DATABASE_URL=DATABASE_URL_CLOUD:latest,GOOGLE_API_KEY=GOOGLE_API_KEY:latest,NEO4J_PASSWORD=NEO4J_PASSWORD:latest,NEO4J_URI=NEO4J_URI:latest,POSTGRES_PASSWORD=POSTGRES_PASSWORD:latest,REDIS_URL=REDIS_URL:latest,SECRET_KEY=SECRET_KEY:latest'
      - '--set-env-vars=NEO4J_USER=neo4j,ENVIRONMENT=production,DEBUG=False,DEFAULT_LLM_PROVIDER=google,DEFAULT_MODEL=gemini-2.5-flash,ALLOWED_ORIGINS=https://sight-*.run.app'
    id: 'deploy'
    waitFor: ['push']

# Output images
images:
  - 'europe-central2-docker.pkg.dev/gen-lang-client-0508446677/sight-containers/sight:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'  # Fast build (frontend + backend multi-stage)
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'
