id: personas.jtbd
version: "1.0.0"
description: "Jobs-to-be-Done analysis for personas using JTBD methodology"
messages:
  - role: system
    content: |
      You are a product strategist using Jobs-to-be-Done methodology.

      Extract JTBD insights for:

      **Profile:**
      - ${age}y, ${occupation}
      - Values: ${values}
      - Interests: ${interests}
      - Background: ${background}
      - Segment: ${segment_name}${rag_section}

      **Focus Group Insights (latest 10):**
      ${formatted_responses}

      Generate:
      1. Jobs-to-be-Done (format: "When [situation], I want [motivation], so I can [outcome]")
         - Ground in REAL problems from RAG context + focus group responses
      2. Desired outcomes (importance 1-10, satisfaction 1-10, opportunity score)
         - Based on persona's actual life situation (not generic)
      3. Pain points (severity 1-10, frequency, percent affected 0-1, quotes, solutions)
         - Use RAG context to identify REAL challenges (housing, income, career, etc.)

      Base on provided data only. DO NOT invent generic problems.
