id: focus_groups.discussion_summary
version: "1.0.0"
description: "Generuje kompleksowe strategiczne podsumowanie dyskusji w grupie fokusowej"
messages:
  - role: system
    content: |
      Jesteś światowej klasy analitykiem badań rynkowych specjalizującym się w syntezie badań jakościowych.
      Twoją rolą jest analiza dyskusji w grupach fokusowych i generowanie strategicznych wniosków dla zespołów produktowych.

      WAŻNE WYTYCZNE:
      - Bądź zwięzły, ale kompleksowy
      - Skup się na actionable insights, nie tylko opisie
      - Identyfikuj wzorce, sprzeczności i zaskakujące odkrycia
      - Uwzględniaj różnice demograficzne w opiniach
      - Dostarczaj strategiczne rekomendacje oparte na danych
      - Używaj profesjonalnego, biznesowego języka
      - Unikaj ogólników - bądź konkretny i oparty na dowodach
  - role: user
    content: |
      Przeanalizuj tę dyskusję w grupie fokusowej i wygeneruj kompleksowe strategiczne podsumowanie.

      **TEMAT GRUPY FOKUSOWEJ:** ${topic}
      **OPIS:** ${description}

      ${demo_context}

      **TRANSKRYPT DYSKUSJI:**
      ${discussion_text}

      ---

      Proszę dostarcz szczegółową analizę w następującej strukturze:

      ## 1. STRESZCZENIE EXECUTIVE (90-120 słów)
      Zsyntetyzuj kluczowe odkrycia w wysokopoziomowy przegląd który odpowiada na:
      - Jaki był ogólny odbiór koncepcji/tematu?
      - Jakie są najbardziej krytyczne wnioski?
      - Jaka jest implikacja strategiczna?

      ## 2. KLUCZOWE WNIOSKI (3-5 punktów, ≤25 słów każdy)
      Wydobądź najważniejsze wzorce i motywy z dyskusji.
      Strukturuj każdy punkt jako: **Etykieta wniosku**: implikacja oparta na dowodach.
      Używaj właściwej składni markdown bold: **tekst** (dwie gwiazdki z obu stron).
      Priorytetyzuj według wpływu biznesowego.

      ## 3. ZASKAKUJĄCE ODKRYCIA (1-2 punkty, ≤20 słów każdy)
      Podkreśl nieoczekiwane lub kontrintuicyjne odkrycia które kwestionują założenia.
      Mogą to być:
      - Sprzeczności między tym co uczestnicy mówią vs. ukryty sentyment
      - Opinie mniejszości które ujawniają przypadki brzegowe
      - Różnice demograficzne których nie przewidziano

      ## 4. ANALIZA SEGMENTÓW
      Rozłóż jak różne segmenty demograficzne (wiek, płeć, zawód) odpowiadały inaczej.
      Strukturuj jako:
      **Nazwa segmentu**: Kluczowy wyróżnik z cytatem/dowodem (≤25 słów)
      Używaj właściwej składni markdown bold: **tekst** (dwie gwiazdki z obu stron).

      ${recommendations_section}

      ## 6. NARRACJA SENTYMENTU (40-60 słów)
      Opisz emocjonalną podróż dyskusji:
      - Jak sentyment ewoluował poprzez pytania?
      - Czy były tematy polaryzujące?
      - Co napędzało pozytywne vs. negatywne reakcje?

      ---

      **WAŻNE:**
      - Używaj konkretnych cytatów i punktów danych jako dowodów
      - Unikaj ogólnego żargonu marketingowego
      - Bądź szczery o słabościach lub obawach podniesionych
      - Rozważ zarówno jawny feedback jak i ukryte wzorce
      - Formatuj używając Markdown dla czytelności (## nagłówki, **bold** wyróżnienia)
