"""Add workflows tables

Revision ID: 4bdf0d123032
Revises: d5e8a3f4b2c1
Create Date: 2025-11-04 11:21:54.947956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bdf0d123032'
down_revision: Union[str, Sequence[str], None] = 'd5e8a3f4b2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('canvas_data', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflows_project_id', 'workflows', ['project_id'], unique=False)
    op.create_index('idx_workflows_owner_id', 'workflows', ['owner_id'], unique=False)
    op.create_index('idx_workflows_status', 'workflows', ['status'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'node_id', name='uq_workflow_step_node')
    )
    op.create_index('idx_workflow_steps_workflow_id', 'workflow_steps', ['workflow_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('current_step_id', sa.UUID(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_step_id'], ['workflow_steps.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_executions_status', 'workflow_executions', ['status'], unique=False)
    op.create_index('idx_workflow_executions_workflow_id', 'workflow_executions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workflow_executions_workflow_id', table_name='workflow_executions')
    op.drop_index('idx_workflow_executions_status', table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index('idx_workflow_steps_workflow_id', table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index('idx_workflows_status', table_name='workflows')
    op.drop_index('idx_workflows_owner_id', table_name='workflows')
    op.drop_index('idx_workflows_project_id', table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
