"""add_dashboard_tables

Revision ID: 4e3cccce934c
Revises: 20251027_project_soft_delete
Create Date: 2025-10-27 10:30:07.974328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3cccce934c'
down_revision: Union[str, Sequence[str], None] = '20251027_project_soft_delete'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('time_to_insight_median', sa.Float(), nullable=True),
    sa.Column('time_to_insight_p90', sa.Float(), nullable=True),
    sa.Column('insight_adoption_rate', sa.Float(), nullable=True),
    sa.Column('active_projects_count', sa.Integer(), nullable=False),
    sa.Column('blocked_projects_count', sa.Integer(), nullable=False),
    sa.Column('persona_coverage_avg', sa.Float(), nullable=True),
    sa.Column('weekly_personas_generated', sa.Integer(), nullable=False),
    sa.Column('weekly_focus_groups_completed', sa.Integer(), nullable=False),
    sa.Column('weekly_insights_extracted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_metrics_metric_date'), 'dashboard_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_dashboard_metrics_user_id'), 'dashboard_metrics', ['user_id'], unique=False)
    op.create_table('action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_created_at'), 'action_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_logs_event_type'), 'action_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_action_logs_project_id'), 'action_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_action_logs_user_id'), 'action_logs', ['user_id'], unique=False)
    op.create_table('project_health_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('health_status', sa.String(length=50), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('blockers', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_health_logs_checked_at'), 'project_health_logs', ['checked_at'], unique=False)
    op.create_index(op.f('ix_project_health_logs_project_id'), 'project_health_logs', ['project_id'], unique=False)
    op.create_table('usage_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('input_cost', sa.Float(), nullable=False),
    sa.Column('output_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('operation_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_metrics_operation_timestamp'), 'usage_metrics', ['operation_timestamp'], unique=False)
    op.create_index(op.f('ix_usage_metrics_operation_type'), 'usage_metrics', ['operation_type'], unique=False)
    op.create_index(op.f('ix_usage_metrics_project_id'), 'usage_metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_usage_metrics_user_id'), 'usage_metrics', ['user_id'], unique=False)
    op.create_table('insight_evidences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('focus_group_id', sa.UUID(), nullable=True),
    sa.Column('insight_type', sa.String(length=100), nullable=False),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adopted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['focus_group_id'], ['focus_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_evidences_focus_group_id'), 'insight_evidences', ['focus_group_id'], unique=False)
    op.create_index(op.f('ix_insight_evidences_project_id'), 'insight_evidences', ['project_id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('focus_group_id', sa.UUID(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['focus_group_id'], ['focus_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_created_at'), 'user_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_notifications_is_read'), 'user_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_user_notifications_notification_type'), 'user_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_user_notifications_project_id'), 'user_notifications', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.drop_index(op.f('idx_audit_action'), table_name='persona_audit_log')
    op.drop_index(op.f('idx_audit_persona_id'), table_name='persona_audit_log')
    op.drop_index(op.f('idx_audit_persona_time_desc'), table_name='persona_audit_log')
    op.drop_index(op.f('idx_audit_timestamp'), table_name='persona_audit_log')
    op.drop_index(op.f('idx_audit_user_id'), table_name='persona_audit_log')
    op.create_index(op.f('ix_persona_audit_log_action'), 'persona_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_persona_audit_log_persona_id'), 'persona_audit_log', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_audit_log_timestamp'), 'persona_audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_persona_audit_log_user_id'), 'persona_audit_log', ['user_id'], unique=False)
    op.drop_index(op.f('idx_persona_deleted_at'), table_name='personas')
    op.drop_index(op.f('idx_persona_deleted_by'), table_name='personas')
    # NOTE: deleted_at and deleted_by columns already exist in projects table
    # (added by migration 20251027_project_soft_delete) - skip duplicate add_column
    op.drop_index(op.f('ix_rag_documents_is_active'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_status'), table_name='rag_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rag_documents_status'), 'rag_documents', ['status'], unique=False)
    op.create_index(op.f('ix_rag_documents_is_active'), 'rag_documents', ['is_active'], unique=False)
    # NOTE: deleted_at and deleted_by columns managed by migration 20251027_project_soft_delete
    # - skip duplicate drop_column in downgrade
    op.create_index(op.f('idx_persona_deleted_by'), 'personas', ['deleted_by'], unique=False)
    op.create_index(op.f('idx_persona_deleted_at'), 'personas', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_persona_audit_log_user_id'), table_name='persona_audit_log')
    op.drop_index(op.f('ix_persona_audit_log_timestamp'), table_name='persona_audit_log')
    op.drop_index(op.f('ix_persona_audit_log_persona_id'), table_name='persona_audit_log')
    op.drop_index(op.f('ix_persona_audit_log_action'), table_name='persona_audit_log')
    op.create_index(op.f('idx_audit_user_id'), 'persona_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_timestamp'), 'persona_audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('idx_audit_persona_time_desc'), 'persona_audit_log', ['persona_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_audit_persona_id'), 'persona_audit_log', ['persona_id'], unique=False)
    op.create_index(op.f('idx_audit_action'), 'persona_audit_log', ['action'], unique=False)
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_project_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_notification_type'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_is_read'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_created_at'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_insight_evidences_project_id'), table_name='insight_evidences')
    op.drop_index(op.f('ix_insight_evidences_focus_group_id'), table_name='insight_evidences')
    op.drop_table('insight_evidences')
    op.drop_index(op.f('ix_usage_metrics_user_id'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_project_id'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_operation_type'), table_name='usage_metrics')
    op.drop_index(op.f('ix_usage_metrics_operation_timestamp'), table_name='usage_metrics')
    op.drop_table('usage_metrics')
    op.drop_index(op.f('ix_project_health_logs_project_id'), table_name='project_health_logs')
    op.drop_index(op.f('ix_project_health_logs_checked_at'), table_name='project_health_logs')
    op.drop_table('project_health_logs')
    op.drop_index(op.f('ix_action_logs_user_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_project_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_event_type'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_created_at'), table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_index(op.f('ix_dashboard_metrics_user_id'), table_name='dashboard_metrics')
    op.drop_index(op.f('ix_dashboard_metrics_metric_date'), table_name='dashboard_metrics')
    op.drop_table('dashboard_metrics')
    # ### end Alembic commands ###
