"""Add target_audience, research_objectives, additional_notes to projects

Revision ID: 722dd8f752ac
Revises: dc069508543e
Create Date: 2025-10-08 12:13:34.569165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722dd8f752ac'
down_revision: Union[str, Sequence[str], None] = 'dc069508543e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('target_audience', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('research_objectives', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('additional_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'additional_notes')
    op.drop_column('projects', 'research_objectives')
    op.drop_column('projects', 'target_audience')
    # ### end Alembic commands ###
