"""Add soft delete fields to focus_groups and surveys

Revision ID: 84a1af0bea7f
Revises: b8e7f3a1c9d2
Create Date: 2025-10-28 13:49:11.460568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '84a1af0bea7f'
down_revision: Union[str, Sequence[str], None] = 'b8e7f3a1c9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_groups', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('focus_groups', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('focus_groups', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_focus_groups_completed_at'), table_name='focus_groups')
    op.create_foreign_key(None, 'focus_groups', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_insight_evidences_insight_type'), table_name='insight_evidences')
    op.alter_column('persona_events', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    op.add_column('surveys', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('surveys', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'surveys', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'deleted_by')
    op.drop_column('surveys', 'deleted_at')
    op.alter_column('persona_events', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.create_index(op.f('ix_insight_evidences_insight_type'), 'insight_evidences', ['insight_type'], unique=False)
    op.drop_constraint(None, 'focus_groups', type_='foreignkey')
    op.create_index(op.f('ix_focus_groups_completed_at'), 'focus_groups', ['completed_at'], unique=False)
    op.drop_column('focus_groups', 'deleted_by')
    op.drop_column('focus_groups', 'deleted_at')
    op.drop_column('focus_groups', 'is_active')
    # ### end Alembic commands ###
