"""Add project_context to focus_groups

Revision ID: c98ab2715cb5
Revises: 20240924_add_persona_name_fields
Create Date: 2025-10-02 13:08:22.570732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98ab2715cb5'
down_revision: Union[str, Sequence[str], None] = '20240924_add_persona_name_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_groups', sa.Column('project_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('focus_groups', 'project_context')
    # ### end Alembic commands ###
