"""add_focus_group_updated_at

Revision ID: ca8ee02c29a1
Revises: 18f44b7e6178
Create Date: 2025-10-30 10:39:38.069387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca8ee02c29a1'
down_revision: Union[str, Sequence[str], None] = '18f44b7e6178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_groups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('focus_groups', 'updated_at')
    # ### end Alembic commands ###
