"""sync_schema_indexes_and_embeddings

Revision ID: d2ad45989efc
Revises: 20251016_remove_kpi_journey
Create Date: 2025-10-16 21:59:36.933128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd2ad45989efc'
down_revision: Union[str, Sequence[str], None] = '20251016_remove_kpi_journey'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_action'), table_name='persona_audit_log')
    op.drop_index(op.f('idx_audit_persona_id'), table_name='persona_audit_log')
    op.drop_index(op.f('idx_audit_persona_time_desc'), table_name='persona_audit_log')
    op.drop_index(op.f('idx_audit_timestamp'), table_name='persona_audit_log')
    op.drop_index(op.f('idx_audit_user_id'), table_name='persona_audit_log')
    op.create_index(op.f('ix_persona_audit_log_action'), 'persona_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_persona_audit_log_persona_id'), 'persona_audit_log', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_audit_log_timestamp'), 'persona_audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_persona_audit_log_user_id'), 'persona_audit_log', ['user_id'], unique=False)
    op.alter_column('persona_events', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    op.drop_index(op.f('idx_persona_deleted_at'), table_name='personas')
    op.drop_index(op.f('idx_persona_deleted_by'), table_name='personas')
    op.drop_index(op.f('ix_rag_documents_is_active'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_status'), table_name='rag_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rag_documents_status'), 'rag_documents', ['status'], unique=False)
    op.create_index(op.f('ix_rag_documents_is_active'), 'rag_documents', ['is_active'], unique=False)
    op.create_index(op.f('idx_persona_deleted_by'), 'personas', ['deleted_by'], unique=False)
    op.create_index(op.f('idx_persona_deleted_at'), 'personas', ['deleted_at'], unique=False)
    op.alter_column('persona_events', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.drop_index(op.f('ix_persona_audit_log_user_id'), table_name='persona_audit_log')
    op.drop_index(op.f('ix_persona_audit_log_timestamp'), table_name='persona_audit_log')
    op.drop_index(op.f('ix_persona_audit_log_persona_id'), table_name='persona_audit_log')
    op.drop_index(op.f('ix_persona_audit_log_action'), table_name='persona_audit_log')
    op.create_index(op.f('idx_audit_user_id'), 'persona_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_timestamp'), 'persona_audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('idx_audit_persona_time_desc'), 'persona_audit_log', ['persona_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_audit_persona_id'), 'persona_audit_log', ['persona_id'], unique=False)
    op.create_index(op.f('idx_audit_action'), 'persona_audit_log', ['action'], unique=False)
    # ### end Alembic commands ###
