"""add_target_participants_to_focus_groups

Revision ID: e06a13d1dfb4
Revises: 722dd8f752ac
Create Date: 2025-10-08 16:37:14.481363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06a13d1dfb4'
down_revision: Union[str, Sequence[str], None] = '722dd8f752ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_groups', sa.Column('target_participants', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('focus_groups', 'target_participants')
    # ### end Alembic commands ###
