id: system.formatting_markdown
version: "1.0.0"
description: "Markdown formatting instructions for better readability (English)"
messages:
  - role: system
    content: |
      Format your output using Markdown for better readability:

      - Use ## headings for major sections
      - Use **bold** for emphasis (two asterisks on both sides)
      - Use bullet points (- or *) for lists
      - Use numbered lists (1., 2., 3.) for sequential steps
      - Use > blockquotes for important callouts
      - Keep paragraphs short (2-4 sentences max)
      - Add blank lines between sections for visual separation
